name: widgets_easier
description: "A new Flutter package project."
version: 0.0.1
homepage: https://flutter-online.top
repository: https://github.com/jacklee1995/widgets_easier

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_easy_animations: ^0.0.2
  flutter_svg: ^2.0.10+1
  gap: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
  assets:
    - assets/images/image_loading_failed.png
    - assets/icons/info.png
    - assets/icons/warning.png
    - assets/icons/success.png
    - assets/icons/error.png
    - assets/icons/right.png
    - assets/icons/confirm.png
    - assets/icons/search.png
    - assets/icons/close.png
    - assets/icons/prohibit.png

screenshots:
  - description: "Widgets Easier Logo."
    path: assets/widgets_easier.png