name: widgets_easier
description: "Widgets Easier is an open-source Flutter component library that comes with multiple pre-built UI components. It aims to make development faster, simpler, and more efficient, turning development into a pleasant experience."
version: 0.0.3
homepage: https://flutter-online.top
repository: https://github.com/jacklee1995/widgets_easier

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_easy_animations: ^0.0.2
  flutter_svg: ^2.0.10+1
  gap: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  
  assets:
    - assets/images/image_loading_failed.png
    - assets/icons/info.png
    - assets/icons/warning.png
    - assets/icons/success.png
    - assets/icons/error.png
    - assets/icons/right.png
    - assets/icons/confirm.png
    - assets/icons/search.png
    - assets/icons/close.png
    - assets/icons/prohibit.png

screenshots:
  - description: "Widgets Easier Logo."
    path: assets/widgets_easier.png